# Generated by Django 3.2 on 2023-06-24 10:15

from django.db import migrations, models
import django_extensions.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Краткое название')),
                ('color', models.CharField(max_length=7, validators=[django_extensions.validators.HexValidator(length=7)], verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Бархатные Тяги',
            },
        ),
    ]
